### ISSUE TITLE
De novo discovery of methylation motifs for metagenomic samples

### ISSUE THREAD

**Issue by BurinkiWU** [fanglab/nanodisco#16]
Hi,

I am trying my best to work out the ***difference.RDS for my metagenomic samples, and I gain 126M of sea9_subset_difference.RDS file. 

However, when I tried to creat the motif files for this dataset, I met the following problem. 

wzq@nanodisco:~$ nanodisco motif -p 4 -b seameta9_example -d analysis/sea9_subset_difference.RDS -o analysis -r reference/seameta_9_wga_trimmed_10kb.fasta -a
[2021-03-10 02:04:41] Prepare output folder.
[2021-03-10 02:04:41] Load supplied current differences.
[2021-03-10 02:04:58] Detect motifs.
[2021-03-10 02:04:58] Processing statistical signal.
Error in do.ply(i) : task 13 failed - "wrong sign in 'by' argument"
Calls: wrapper.motif.detection ... ddply -> ldply -> llply -> <Anonymous> -> <Anonymous>
Execution halted

Looking forward to the solution.

Best,

**Comment by touala** [comment]
Hi @WUZIQI,

I can't reproduce this issue and the R error message is not informative. Are you using the latest `nanodisco release` (i.e. `v1.0.2` from `nanodisco version`)? If not please update and try this command again.

If you would like to privately share the fasta reference and the difference.RDS files (to alan.tourancheau@mssm.edu), it would be extremely helpful for debugging and sort out this issue.

Best,

Alan
