### ISSUE TITLE
no WGA data

### ISSUE THREAD

**Issue by s4251484** [fanglab/nanodisco#21]
Hi

I used Illumina data for Nanopolish. is there any way to use nanodisco without having the WGA data?
i understand the concerns about some methylation motifs have weak signal to noise ratio etc. 

Thanks!

**Comment by touala** [comment]
Hi @s4251484,

No, currently, there isn't a way to use ``nanodisco`` reliably without having WGA data and that for two considerations described in our [FAQ](https://nanodisco.readthedocs.io/en/latest/faq.html#q-wga).

Please let me know if you have more questions,

Alan
