### ISSUE TITLE
Suitable to compare isogenic methylation profiles?

### ISSUE THREAD

**Issue by lthomp06** [fanglab/nanodisco#25]
Hello,

I am wondering if nanodisco is a suitable program to compare the methylation patterns of two isogenic strains of E. coli. Would this be possible through the methylation binning of metagenomic contigs functions?

Cheers, 
Laura

**Comment by touala** [comment]
Hello Laura,

I don't think I have all the information to respond accurately to your question. I'm assuming you have/want to sequence(d) two isogenic strains of *E. coli* coming from the same biological sample. If the strains can be assembled in two mostly distinct set of contigs (i.e. enough difference between genome, likely in non-coding regions if they are isogenic), and if the methylation motifs are different (e.g. G6mATC unique to strain A), then yes the methylation binning function should work.

Could you give me more information about the biological context from which the sample comes from? Is it done in an *in vitro* setup where you mixed strains? Are there other strains/species in the sample?

Regards,

Alan
