### ISSUE TITLE
Issue when performing 'nanodisco characterize'

### ISSUE THREAD

**Issue by lorenzocasbarra** [fanglab/nanodisco#30]
Dear Dr. Tourancheau,
I'm a phd student approaching for the first time to nanopore sequencing and DNA methylation characterization. I was trying to use nanodisco out of curiosity and everything proceeded fine until the typing and fine mapping step. In this step I performed the following call:
#
nanodisco characterize -p 20 -b Ecoli -d dataset/EC_subset_difference.RDS -o analysis/motif_detection/Ecoli_motifs -m CTGRYG,AWTMWTKAWAAAWR,CRCCAKCWGCGCRA,CTKCTCGKYAAAAC,ACWTCGMTCCSKGC -t nn,rf,knn -r reference/Escherichia_coli_ATCC_35218.fasta
Which returned the following error:
Error in { :
task 2 failed - "arguments imply differing number of rows: 1, 0"
Calls: find.signature.center -> %do% -> <Anonymous>
Execution halted
#
I also tried the following:
nanodisco characterize -p 20 -b Ecoli -d dataset/EC_subset_difference.RDS -o analysis/motif_detection/Ecoli_motifs -m CTGRYG -t nn,rf,knn -r reference/Escherichia_coli_ATCC_35218.fasta
Which returned the following error:
Error in { :
task 2 failed - "arguments imply differing number of rows: 1, 0"
Calls: find.signature.center -> %do% -> <Anonymous>
Execution halted
#
Hoping that you can help me with some advice, I provide a  txt file explaining more in detail the calls I performed in my pipeline (https://drive.google.com/file/d/1ZMJxPnyO_ioS6wL1YQEofnq8mRjJMBv6/view?usp=sharing). You can also find my workspace compressed at the following link (which is approximatly 1GB):
https://drive.google.com/file/d/1rtiDOthSBrA_j6-VrqxxgowXvjBcs1rv/view?usp=sharing
Thank you for your time and attention.
Kind regards, Lorenzo Casbarra

**Comment by touala** [comment]
Hello Lorenzo,

I'd like to apologize for making you wait for so long and thank you for sending your workspace.

Looking at the fast5 shared, I can see that the genome must be only shallowly covered. Is this the full dataset? If it is, `nanodisco` won't be able to work as it require at least 5x to compute statistics. This results in `dataset/EC_subset_difference.RDS` being mostly empty (many `NA` for all statistics). Otherwise, after a quick look, I think the commands are fine.

Alan

**Comment by lorenzocasbarra** [comment]
Hello Alan,
Sorry for my late response and thank you for your help, I really appreciate
it.
Effectively, the fast5 used doesn't represent the full dataset. I just
tried out nanodisco with it, since it is the only basecalled fast5 at my
disposal. I'm hoping to basecall the others in a matter of time and I'll
let you know if any other issues arise.
Thanks again!
- Lorenzo -

Il giorno mer 1 dic 2021 alle ore 23:43 touala ***@***.***>
ha scritto:
