### ISSUE TITLE
nanodisco score

### ISSUE THREAD

**Issue by asershova** [fanglab/nanodisco#35]
Dear Alan,

Thank you for the great tool. Could you please explain how a methylation score in the Motifs_occurrences_scores file is calculated?
Regards,
Anna

**Comment by touala** [comment]
Hello @asershova,

Scores found in `Motifs_occurrences_scores_<base_name>.tsv` correspond to maximum of the current difference averaged for a `[-2, +3]` window around the modified base in each motif occurrences (by default). If this help, you can find the code [here](https://github.com/fanglab/nanodisco/blob/26239461012af3bc8fd63fb00c9c3a29c1d4ba48/code/metagenome_analysis_functions.R#L2714). Those scores were computed in the intent to evaluate putative misassemblies in metagenomic assemblies (example in [Figure 5d](https://www.nature.com/articles/s41592-021-01109-3/figures/5)). 

Best,

Alan
