### ISSUE TITLE
nanodisco characterize

### ISSUE THREAD

**Issue by linuxxue** [fanglab/nanodisco#37]
Hi, when I running  characterize, there are the following tips:
![35941560e87044649f3653977a5e636](https://user-images.githubusercontent.com/75844050/154644630-46ee0d4e-3b91-490c-b126-50374e97a80d.png)

Any suggestion about a solution?
Thanks a lot.

**Comment by touala** [comment]
Hello @linuxxue,

From my experience, if both native and WGA datasets were basecalled with the same basecaller version, this can be ignored. Please let me know if the characterization command do not proceed properly.

Best,

Alan

**Comment by linuxxue** [comment]
Thanks a lot.
