### ISSUE TITLE
multiplexed libraries with multiple taxa

### ISSUE THREAD

**Issue by nick-youngblut** [fanglab/nanodisco#38]
It seems that nanodisco assumes that the fast5 files all contain sequence data from the same reference (e.g., `nanodisco preprocess -r <reference_genome>`). What about instances where multiple strains/species/genera/etc are multiplexed on the same nanopore run? I would think that multiplexing would be common for modified base identification, given that sequencing just one microbial genome per nanopore run is generally a waste of resources.

**Comment by fanggang** [comment]
Thank you for your interest in our work. Indeed, multiplexing is encouraged for doing bacterial methylation analysis with nanodisco, for both MinION and Flongle. The strains presented in our paper were also sequenced with multiplexing. Regarding your question: the current solution would probably be first de-multiplexing first and then use nanodisco (take de-multiplexed native and WGA data as input). Hope this helps.

**Comment by nick-youngblut** [comment]
Thanks @fanggang! I don't see anything in the [documentation](https://nanodisco.readthedocs.io/en/latest/overview.html) on dealing with multiplexed data. It would be great to have some info in the primary nanodisco docs on how to go about first demultiplex and then use nanodisco on the demultiplexed data. For instance, I'm guessing that many people don't know how to produce "de-multiplexed native" data.

**Comment by fanggang** [comment]
Great feedback. We will provide this information to make it easier. 

Gang

**Comment by touala** [comment]
Hello @nick-youngblut,

Thank you very much for the suggestion. We added an entry in our FAQ section with some help to process those kind of datasets (please see [Q14](https://nanodisco.readthedocs.io/en/latest/faq.html#q-demux)).

Alan
