### ISSUE TITLE
Columns in nanodisco score output

### ISSUE THREAD

**Issue by molleraj** [fanglab/nanodisco#40]
Hi - I have a quick question about the nanodisco score output. What does each output file column represent? This is not stated in the docs (https://nanodisco.readthedocs.io/en/latest/commands_details.html?highlight=coverage#score). 

Any help would be greatly appreciated!

Thanks,
Jon

**Comment by touala** [comment]
Hi @molleraj,

Thank you very much for the feedback. I've included a description in the documentation. In addition, I've briefly talked about the score in two other issues (#31 and #35) which could be informative.

If you have any additional questions, feel free to reach back to me,

Alan

**Comment by molleraj** [comment]
Hey Alan @touala 

You are welcome! Thank you for doing this - much appreciated. I will let you know if I do, thanks again.

Jon @molleraj

**Comment by molleraj** [comment]
Hey Alan,

I checked your description and I do have one further question. How is coverage over a motif calculated for WGA and native read data?

Thanks,
Jon

**Comment by touala** [comment]
Hi @molleraj,

This is obviously quite late to respond but for the sack of completeness, the coverage is computed from the number of map events on each genomic position. The code in found [here](https://github.com/fanglab/nanodisco/blob/master/code/difference_functions.R#L1001).

Best,

Alan
