### ISSUE TITLE
Error in preprocess

### ISSUE THREAD

**Issue by ilhdkk** [fanglab/nanodisco#41]
hello! when I run the step preprocess I got an error, the task keeps running on but there are not any results in the output directory.
root@nanodisco:/$ nanodisco preprocess -p 1 -f /nano40/9Sfast5pass -s 9Sfast5pass -o ./9Sresult -r nano40/LT2.fasta
[2022-04-22 19:40:47] Localize all fast5 files.
[2022-04-22 19:40:47]     Found 22 fast5 files.
[2022-04-22 19:40:47] Extract sequences from fast5.
 Processed fast5 [-------------------------]   0% eta:  ?s (elapsed: 00:00:00)
Any help would be greatly appreciated!

Thanks,
kk

**Comment by ilhdkk** [comment]
root@nanodisco:/$ nanodisco preprocess -p 1 -f /nano40/9Sfast5pass -s 9Sfast5pass -o ./9Sresult -r nano40/LT2.fasta
[2022-04-22 19:40:47] Localize all fast5 files.
[2022-04-22 19:40:47]     Found 22 fast5 files.
[2022-04-22 19:40:47] Extract sequences from fast5.
Error in pb_tick(self, private, len, tokens) : !self$finished is not TRUE
Calls: extract.sequence ... terminate.progress.bar -> <Anonymous> -> pb_tick -> stopifnot
Execution halted
Unexpected error during read extraction process.

**Comment by touala** [comment]
Hi @ilhdkk,

Thank you for providing the log. Could you try running the same command on a directory with only one fast5. Please note that, in the current version, the `Extract sequences from fast5` step can be quite slow, without visible progress. If this still do not work, do you mind providing me one of the fast5, so I can run test on my side (alan.tourancheau[at]bio.ens.psl.eu)?

Alan

**Comment by ilhdkk** [comment]
Hi @touala ,
I run the same command on a directory with only one fast5 and that worked, thank you for your advice!
All the best ,
kk
