### ISSUE TITLE
Open and parse .RDS file

### ISSUE THREAD

**Issue by yxhuang623** [fanglab/nanodisco#42]
Hi, I'm trying to open and visualize the .RDS file but I failed to find a right way to do it. Could you please give me some suggestions? Such information are very important for me to localize the moitifs in the genome of my dataset. Thank you so much!

**Comment by touala** [comment]
Hi @yxhuang623,

Those `.RDS` files are a standard R data format which allow saving data structure. You can open it within `R` with:
```R
 df <- readRDS("<path_RDS_file>")
```

You can find a great write up [here](http://www.sthda.com/english/wiki/saving-data-into-r-data-format-rds-and-rdata) for more information. Please let me know if you have other questions.

Best,

Alan
