### ISSUE TITLE
characterize

### ISSUE THREAD

**Issue by mei-du** [fanglab/nanodisco#45]
Hi,

I'm getting this error - any clarification would be appreciated. Thank you!

![image](https://user-images.githubusercontent.com/58542302/169446277-d6f88259-0ea8-4e30-b219-9a846352683e.png)

**Comment by touala** [comment]
Hi @mei-du,

R error messages are rarely informative, and I'm not sure what is the issue. Is it possible to share all the input files from the command with an issue at alan.tourancheau [at] bio.ens.psl.eu?

Alan

**Comment by touala** [comment]
Hi @mei-du,

It look like your input file from `nanodisco difference` are near empty. Feel free to reopen the issue if necessary.

Best,

Alan

**Comment by DelphIONe** [comment]
Hi,

I have the same issue. merge_difference.RDS size is ~144Mb. Only the pdf files have been generated.
Nanodisco was ok on the first two strains but I have this problem on the third and I don't understand why.

Can you help me to resolve that please ? Thanks!
