### ISSUE TITLE
Only one motif detected

### ISSUE THREAD

**Issue by tongzhouxu** [fanglab/nanodisco#54]
Hi,

Thanks for developing nanodisco. It is a great tool. We used nanodisco to look for mythlations in a Listeria strain but were only able to get one motif and the prediction score for the mythlated site is also quite low (please see attached). The coverage for the sequecing is aound 150x. I was wondering if would recommend increasing coverage to get more possible motifs.

Thanks,
Tongzhou
[Motifs_classification_0h_nn_model.pdf](https://github.com/fanglab/nanodisco/files/9974867/Motifs_classification_0h_nn_model.pdf)

**Comment by fanggang** [comment]
Thank you for your interest and email, Tongzhou.

150X is fairly good from our experience. Although the score is not
high (it happens sometime), the heatmap you sent looks very clean (the
type and fine mapped base both clear). GKATMC is a nice palindrome,
very likely an authentic motif in this strain.

Not sure which Listeria species it is, but REBASE shows that some
Listeria species/strains have very few methylation motifs (some other
strains have more). You do not necessarily have to find many motifs.

Hope this helps.
Gang

**Comment by tongzhouxu** [comment]
Hi Dr. Fang @fanggang ,

Thank you so much for your quick reply! The strain we sequenced is Listeria monocytogenes H7550-cds and I found only one motif GTATCC on REBASE which seems concordant with our results. I would also like to know if I can get all the motif methylation sites with nanodisco. I see there is a motifs_22bp_top_2000_peaks.fasta file with genome locations and I wonder if I can get all the peaks for one motif or I need to explore the current difference file.

Thanks,
Tongzhou

**Comment by fanggang** [comment]
Tongzhou, great knowing that your results look consistent with
expected entries in REBASE. Alan has more experience about your
question on fasta. At the high level, we do not recommend interpreting
individual site level methylation from nanopore data yet, at least not
from nanodisco, as we explained in Q7 in FAQ:
https://nanodisco.readthedocs.io/en/latest/faq.html
Hope this helps,
Gang

**Comment by tongzhouxu** [comment]
Thank you Dr. Fang so much for your explanation!
