### ISSUE TITLE
Error with Nanopolish

### ISSUE THREAD

**Issue by oliveira-lab** [fanglab/nanodisco#58]
Hi Alan,

I installed nanodisco on the cluster and is working fine on your test dataset.
However, upon running it in one of my datasets, I am getting all eventalign files empty (as below):

Warning messages:
1: In fread(path_fwd, header = T, sep = "\t", stringsAsFactors = TRUE,  :
  File '/home/nanodisco/analysis/difference_subset/tmp.281.DDG_AAAA_ONT_1_FAR92030_A_WGA.fwd.eventalign' has size 0. Returning a NULL data.table.
2: In fread(path_rev, header = T, sep = "\t", stringsAsFactors = TRUE,  :
  File '/home/nanodisco/analysis/difference_subset/tmp.281.DDG_AAAA_ONT_1_FAR92030_A_WGA.rev.eventalign' has size 0. Returning a NULL data.table.
3: In fread(path_fwd, header = T, sep = "\t", stringsAsFactors = TRUE,  :
  File '/home/nanodisco/analysis/difference_subset/tmp.281.DDG_AAAA_ONT_1_FAR54859_A_NAT.fwd.eventalign' has size 0. Returning a NULL data.table.
4: In fread(path_rev, header = T, sep = "\t", stringsAsFactors = TRUE,  :
  File '/home/nanodisco/analysis/difference_subset/tmp.281.DDG_AAAA_ONT_1_FAR54859_A_NAT.rev.eventalign' has size 0. Returning a NULL data.table.

When I look at one of the event align.err files they have the following error:

[readdb] num reads: 903, num reads with path to fast5: 903
nanopolish: src/nanopolish_squiggle_read.cpp:321: void SquiggleRead::load_from_raw(fast5_file&, uint32_t): Assertion `rt.n > 0' failed.

I was able to find this issue described in the nanopolish GitHub page:

https://github.com/jts/nanopolish/issues/403

And it seems to indicate that is a problem with nanopolish version. Do you confirm? I am using version 0.11.0

Still, I am still banging my head around this.
Can you help ?

All the best,
Pedro

**Comment by oliveira-lab** [comment]
Hi Alan,

I found the problem and solution.
This arises because I was using VBZ compressed fast5 files. I converted them to GZIP, and it worked properly.
You may close the issue!
Thanks!
Pedro

**Comment by touala** [comment]
Thank you Pedro for providing the solution.
