### ISSUE TITLE
reference metagenome file

### ISSUE THREAD

**Issue by yfan2012** [fanglab/nanodisco#6]
Hi,

I was wondering how you recommend the reference metagenome file be generated when doing the 'generate current differences' step for metagenomic binning. Can the metagenomic contigs for my sample of interest be used, or is it necessary to combine reference quality genomes perhaps based on the organism abundance in my sample? If contigs can be used, do you have recommendations about using an assembly constructed from the wga run, the native run, or combining the reads from both runs? Thanks in advance!

**Comment by touala** [comment]
Hello @yfan2012,

Thank you for your interest in `nanodisco`.

We briefly discuss the choice of genome/metagenome to use in the [question #3 of our FAQ](https://nanodisco.readthedocs.io/en/latest/faq.html#q-ref-genome). To summarize, you should use the closest matching sequences to your sample. In most cases, a good choice would be using a *de novo* assembly from native nanopore data, which is further polished either with WGA nanopore reads or Illumina/PacBio reads (correcting methylation-related consensus errors). 

For your specific question, if you're working with a mock microbiome or a heavily studied sample, then using matching reference quality genomes could indeed be an option but it's not widely applicable. 

For broad applications to microbiome samples, we recommend the following workflow as described in [our study](https://www.biorxiv.org/content/10.1101/2020.02.18.954636v1):
- *De novo* assembly with [Flye](https://github.com/fenderglass/Flye) using native nanopore reads. Including WGA reads increased our *de novo* assembly fragmentation.
- Polishing with [racon](https://github.com/isovic/racon) using native nanopore reads. Filled larger gaps not fixable with `nanopolish`.
- Polishing with [nanopolish](https://github.com/jts/nanopolish) using native nanopore reads.
- Polishing with [nanopolish](https://github.com/jts/nanopolish) using WGA nanopore reads. Fixed methylation-related consensus errors.

Please let me know if this answers your question or if you have any additional ones.

Alan

**Comment by yfan2012** [comment]
Perfect, thanks very much!
