### ISSUE TITLE
Issue with nanodisco difference in detailed tutorial

### ISSUE THREAD

**Issue by ghost** [fanglab/nanodisco#62]
Hello,

I am working through the detailed tutorial (via docker container) and am running into an issue with step 1.3. I have been following the steps exactly, and am getting this output when I run the nanodisco difference command:

```
Computers / CPU cores / Max jobs to run
1:local / 4 / 2

Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
local:2/0/100%/0.0s /bin/sh: 1: compute_difference: not found
local:2/1/100%/1.0s /bin/sh: 1: compute_difference: not found
local:2/2/100%/0.5s /bin/sh: 1: compute_difference: not found
local:2/3/100%/0.3s /bin/sh: 1: compute_difference: not found
local:2/4/100%/0.2s /bin/sh: 1: compute_difference: not found
local:2/5/100%/0.2s /bin/sh: 1: compute_difference: not found
local:2/6/100%/0.2s /bin/sh: 1: compute_difference: not found
local:2/7/100%/0.1s /bin/sh: 1: compute_difference: not found
local:2/8/100%/0.1s /bin/sh: 1: compute_difference: not found
local:1/9/100%/0.1s /bin/sh: 1: compute_difference: not found
local:0/10/100%/0.1s 
```

Any insight on how to successfully run this command would be greatly appreciated!

**Comment by touala** [comment]
Hi @starkeynight,

Thank you for trying `nanodisco`. This is the first time I see this error. I had report from users using `nanodisco` with docker so I don't think this is a problem (I use `singularity`). Would you be able to restart from a fresh container or try `singularity` instead?

Best,

Alan

**Comment by ghost** [comment]
Hi Alan, Thank you for your response. I ended up being able to run this by setting the -nj, -nc, and -p tags to 1, while still using docker.

**Comment by touala** [comment]
Thank you for the feedback. So I'm assuming you were running out of ressources which broke the processus... Good to know if a similar issue is reported.

Best,

Alan
