### ISSUE TITLE
chunk_info -> Error in scan

### ISSUE THREAD

**Issue by duceppemo** [fanglab/nanodisco#75]
Hi,
Not sure why but I keep having the following error using the `chunk_info` command on my reference genome:
```
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  line 2 did not have 8 elements
Calls: generate.genome.chunks.information -> read.table -> scan
Execution halted
```
I don't get this error with the provided reference in the `get_data_bacteria` dataset. Do you have any idea why I'm getting this error? My reference is NZ_CP059443.1.

**Comment by duceppemo** [comment]
I re-downloaded the reference genome and it somehow fixed my problem. I ran a `diff` on the two files and nothing obvious pops out. Go figure. Problem solved. It would have been good to know what that file is causing problem.

**Comment by touala** [comment]
Hi @duceppemo,

Thank you for the feedback. This could be helpful to other users.

Alan
