### ISSUE TITLE
List of common methylation motifs is missing

### ISSUE THREAD

**Issue by LynnLy** [fanglab/nanodisco#8]
Hi! I'm trying to do microbiome methylation binning with the automated approach without specific de novo discovered motifs. I'm using the docker installation as we don't have Singularity set up right now. Where can I find `list_motifs.RDS` ?

Thank you!
Lynn

```
root@nanodisco:~$ nanodisco profile -p 20 -r reference/6plex.fasta -d analysis/Mix2_6plex_difference.RDS -w analysis/preprocessed/Mix2_wga_subsample.cov -n analysis/preprocessed/
Mix2_native_subsample.cov -b Mix2_6plex_all -o analysis/binning -a all
List of common methylation motifs (/home/nanodisco/reference/list_motifs.RDS) is missing. Please reach out for help on GitHub.```

**Comment by touala** [comment]
Hi Lynn,

The `list_motifs.RDS` file is part of the files downloaded during the image generation, so on the server side (hub.docker.com or singularity-hub.org). We are not sure why it is missing but no worry, you can retrieve it directly with:

```sh
# Start a docker container
docker run -it --name <my_analysis> fanglab/nanodisco bash

# Download the default datasets
wget -q https://nanodiscodata.s3.us-east-2.amazonaws.com/data_default.tar.gz

# Extract the missing file
tar -zxf data_default.tar.gz -C /home nanodisco/reference/list_motifs.RDS && rm data_default.tar.gz
```
Please let us know if this can fix your issue.

Alan

**Comment by LynnLy** [comment]
Thank you, this fixes it!

It might be missing because my reference directory was bound with `-v /full_path/to/my_genomes:/home/nanodisco/reference`.
